language: c
os : linux
jobs:
  include:
    - os: windows
      arch: amd64
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - dist: xenial
      arch: amd64
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - dist: bionic
      arch: amd64
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - dist: focal
      arch: amd64
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world